# Generated by Django 3.2.8 on 2021-10-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuggerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('role', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField()),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=10)),
                ('ticket_type', models.CharField(max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bugger.buggeruser')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugger.project')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bugger.buggeruser')),
            ],
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_changed', models.CharField(max_length=30)),
                ('old_value', models.CharField(max_length=30)),
                ('new_value', models.CharField(max_length=30)),
                ('date_changed', models.DateTimeField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugger.buggeruser')),
                ('ticket_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugger.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugger.buggeruser')),
                ('ticket_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugger.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugger.buggeruser')),
                ('ticket_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugger.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_attachments',
            field=models.ManyToManyField(blank=True, to='bugger.TicketAttachment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_comments',
            field=models.ManyToManyField(blank=True, to='bugger.TicketComment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_events',
            field=models.ManyToManyField(blank=True, to='bugger.TicketEvent'),
        ),
        migrations.AddField(
            model_name='project',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='bugger.Ticket'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, to='bugger.BuggerUser'),
        ),
    ]
