# Generated by Django 3.2.8 on 2021-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buggeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
