# Generated by Django 3.2.8 on 2021-11-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugger', '0002_alter_buggeruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugger.buggeruser'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bugger.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugger.buggeruser'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bugger.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugger.buggeruser'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='ticket_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bugger.ticket'),
        ),
    ]
